"""shop

Revision ID: 5a1a816bfdb1
Revises: 8000929c7f0b
Create Date: 2023-12-06 20:05:46.330583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1a816bfdb1'
down_revision = '8000929c7f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('imageFile', sa.String(length=200), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=True),
    sa.Column('jersey_no', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchase', sa.Column('user_name', sa.String(length=50), nullable=False))
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'purchase', 'user', ['user_id'], ['id'])
    op.drop_column('purchase', 'user_name')
    op.drop_table('shop')
    # ### end Alembic commands ###
